### PR TITLE
Init Wrapper

### PR DESCRIPTION
**Pull request by JeromeK13**
Signed-off-by: Jérôme Krell <jerome.krell@bluewin.ch>

All information can be found here:
https://github.com/hyperledger/indy-sdk/pull/1803

### CODE REVIEW

**Comment by JeromeK13** [comment]
@dbluhm @jovfer 
Any Updates on this PR?

**Comment by JeromeK13** [comment]
https://wiki.hyperledger.org/pages/viewpage.action?pageId=24773976

Hey Guys and @dbluhm 

I have seen, that you have our Wrapper as an "Upcoming Releases and Work Updates". Let me know if I should join any meeting or get you guys some more information.

Greets
Jerome

**Comment by andrewwhitehead** [comment]
I think this is an elegant approach to an Indy SDK wrapper, but it duplicates the functionality of the Python wrapper contained in Indy SDK as opposed to building upon it.

Structurally, there's no reason that I can see for making all the API endpoints static methods of classes (like Anoncreds and Did), that's just adding another namespace within the package for no advantage. It seems that this could easily support the current API (`indy.did.create_and_store_my_did` vs `sbca_wrapper.did.Did.create_and_store_did`) with simply less boilerplate required for defining new methods, and potentially less bugs introduced by doing type coercion manually.

Personally, I think this belongs back in Indy SDK but as an API-compatible refactor of the existing wrapper.

**Comment by JeromeK13** [comment]
Hey

Thanks for your review @andrewwhitehead. I see your points, so here are my thoughts:

For the Wrapper-Usage you can do `sbca_wrapper.DID.create_and_store_did` so no need to have that "double DID" import.
Also since the most development is moving to aries I don't know if it makes sense to get this into Indy. See Chat [here](https://chat.hyperledger.org/channel/indy?msg=zHHqDCmbJhTSJM8Mv)
And also the Indy Guys said it would fit into Aries and the other side around.

Looking forward to finding a consensus on that ;)

Jérôme

**Pull request closed without merging**
